services:
  - type: web
    name: save-restricted-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION
        sync: false
      - key: AUTH
        sync: false
      - key: FORCESUB
        sync: false
      - key: PORT
        value: 10000
